=== thousandparsec-obsolete/web/downloads/downloads.dtd
<!ELEMENT downloads (platforms, rulesets, products) >

<!ELEMENT longname (#PCDATA) >
<!ELEMENT description (#PCDATA) >

<!ELEMENT platforms (platform*) >
<!ELEMENT platform (longname, description?) >
<!ATTLIST platform name ID #REQUIRED >

<!ELEMENT rulesets (ruleset*) >
<!ELEMENT ruleset (longname, description?) >
<!ATTLIST ruleset name ID #REQUIRED >

<!ELEMENT instruction (#PCDATA) >
<!ELEMENT requirement (#PCDATA) >
<!ELEMENT file (#PCDATA) >
<!ATTLIST file href CDATA #REQUIRED >

<!ELEMENT rules (#PCDATA) >
<!ELEMENT package (instruction*, requirement*, file*) >
<!ATTLIST package platform CDATA #REQUIRED version CDATA #REQUIRED >

<!ELEMENT products (category*) >
<!ELEMENT category (longname, description?, product*) >
<!ATTLIST category name ID #REQUIRED >

<!ELEMENT product (longname, description, rules*, package*) >
<!ATTLIST product name ID #REQUIRED visible CDATA #REQUIRED >

=== thousandparsec-obsolete/web/downloads/downloads.xml
<?xml version="1.0"?>
<!DOCTYPE downloads SYSTEM "downloads.dtd">
<downloads>
    <platforms>
        <platform name="win32">
            <longname>Microsoft Windows</longname>
        </platform>
        <platform name="macosx">
            <longname>MacOS X</longname>
        </platform>
        <platform name="linux-ubuntu">
            <longname>Ubuntu Linux</longname>
        </platform>
        <platform name="linux-debian">
            <longname>Debian GNU/Linux</longname>
        </platform>
        <platform name="linux-redhat">
            <longname>Red Hat Linux</longname>
        </platform>
        <platform name="linux-gentoo">
            <longname>Gentoo Linux</longname>
        </platform>
        <platform name="inplace">
            <longname>Inplace</longname>
        </platform>
        <platform name="source">
            <longname>Source</longname>
        </platform>
        <platform name="developer">
            <longname>Developers</longname>
        </platform>
    </platforms>
    <rulesets>
        <ruleset name="minisec">
            <longname>MiniSec</longname>
        </ruleset>
        <ruleset name="minisecplus">
            <longname>MiniSec Plus</longname>
        </ruleset>
        <ruleset name="mtsec">
            <longname>MTSec</longname>
        </ruleset>
        <ruleset name="timtrader">
            <longname>TIM Trader</longname>
        </ruleset>
        <ruleset name="tae">
            <longname>Tigris and Euphrates</longname>
        </ruleset>
        <ruleset name="rfts">
            <longname>Reach for the Stars</longname>
        </ruleset>
        <ruleset name="risk">
            <longname>Risk</longname>
        </ruleset>
    </rulesets>
    <products>
        <category name="client">
            <longname>Clients</longname>
            <product name="tpclient-pywx" visible="yes">
                <longname>tpclient-pywx</longname>
                <description>Main graphical client implemented in Python with wxWidgets.</description>
                <package platform="win32" version="0.3.1.1">
                    <requirement>Windows 98 (Windows 2000/XP preferred)</requirement>
                    <requirement>50 MB disk space</requirement>
                    <requirement>1024x768 or greater resolution</requirement>
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.wxpython.org"&gt;wxPython&lt;/a&gt;</requirement>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pywx-0.3.1.1-setup.exe">Download from SourceForge</file>
                </package>
                <package platform="macosx" version="0.3.1.1">
                    <requirement>Intel- or PowerPC-based Mac</requirement>
                    <requirement>Mac OS X 10.4.1 or higher preferred</requirement>
                    <requirement>200 MB disk space</requirement>
                    <requirement>1024x768 or greater resolution</requirement>
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.wxpython.org"&gt;wxPython&lt;/a&gt;</requirement>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pywx_0.3.1.1.dmg">Download from SourceForge</file>
                </package>
                <package platform="linux-ubuntu" version="0.3.1.1">
                    <instruction>Run &lt;code&gt;sudo apt-get install tpclient-pywx&lt;/code&gt;.</instruction>
                </package>
                <package platform="linux-debian" version="0.3.1.1">
                    <instruction>Run &lt;code&gt;sudo apt-get install tpclient-pywx&lt;/code&gt;.</instruction>
                </package>
                <package platform="linux-gentoo" version="0.3.1.1">
                    <instruction>Run &lt;code&gt;emerge -av tpclient-pywx&lt;/code&gt;.</instruction>
                </package>
                <package platform="inplace" version="0.3.1.1">
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.wxpython.org"&gt;wxPython&lt;/a&gt;</requirement>
                    <file href="http://thousandparsec.net/tp/downloads/tpclient-pywx/tpclient-pywx-0.3.1.1-inplace.tar.bz2">Download from Thousand Parsec Website</file>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pywx-0.3.1.1-inplace.tar.bz2">Download from SourceForge</file>
                </package>
                <package platform="source" version="0.3.1.1">
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.wxpython.org"&gt;wxPython&lt;/a&gt;</requirement>
                    <file href="http://thousandparsec.net/tp/downloads/tpclient-pywx/tpclient-pywx-0.3.1.1.tar.bz2">Download from Thousand Parsec Website</file>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pywx-0.3.1.1.tar.bz2">Download from SourceForge</file>
                </package>
                <package platform="developer" version="-">
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.wxpython.org"&gt;wxPython&lt;/a&gt;</requirement>
                    <file href="http://git.thousandparsec.net/gitweb/gitweb.cgi?p=tpclient-pywx.git;a=summary">Git Repository</file>
                </package>
            </product>
            <product name="tpclient-pyogre" visible="yes">
                <longname>tpclient-pyogre</longname>
                <description>A client which uses a 3D interface based on the Ogre3d library.</description>
                <package platform="win32" version="0.0.1">
                    <requirement>Windows 98 (Windows 2000/XP preferred)</requirement>
                    <requirement>50 MB disk space</requirement>
                    <requirement>1024x768 or greater resolution</requirement>
                    <requirement>3D accelerator graphics card</requirement>
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.python-ogre.org"&gt;Python Ogre&lt;/a&gt;</requirement>
                    <file href="http://thousandparsec.net/tp/downloads/tpclient-pyogre/tpclient-pyogre-0.0.1-setup.exe">Download from Thousand Parsec Website</file>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pyogre-0.0.1-setup.exe">Download from SourceForge</file>
                </package>
                <package platform="source" version="0.0.1">
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.python-ogre.org"&gt;Python Ogre&lt;/a&gt;</requirement>
                    <file href="http://thousandparsec.net/tp/downloads/tpclient-pyogre/tpclient-pyogre-0.0.1.tar.gz">Download from Thousand Parsec Website</file>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpclient-pyogre-0.0.1.tar.gz">Download from SourceForge</file>
                </package>
                <package platform="developer" version="-">
                    <requirement>&lt;a href="http://www.python.org"&gt;Python&lt;/a&gt; and &lt;a href="http://www.python-ogre.org"&gt;Python Ogre&lt;/a&gt;</requirement>
                    <file href="http://git.thousandparsec.net/gitweb/gitweb.cgi?p=tpclient-pyogre.git;a=summary">Git Repository</file>
                </package>
            </product>
            <product name="galaxie" visible="no">
                <longname>Galaxie</longname>
                <description>A client which uses the E libraries (also includes a helper AI!).</description>
                <package platform="developer" version="-">
                    <file href="http://git.thousandparsec.net/gitweb/gitweb.cgi?p=galaxie.git;a=summary">Git Repository</file>
                </package>
            </product>
            <product name="parsek" visible="no">
                <longname>Parsek</longname>
                <description>A client for KDE 4 written in C++.</description>
                <package platform="developer" version="-">
                    <file href="http://git.thousandparsec.net/gitweb/gitweb.cgi?p=parsek.git;a=summary">Git Repository</file>
                </package>
            </product>
        </category>
        <category name="server">
            <longname>Servers</longname>
            <product name="tpserver-cpp" visible="yes">
                <longname>tpserver-cpp</longname>
                <description>A Thousand Parsec server implemented in C++ (currently the main server).</description>
                <rules>minisec</rules>
                <rules>mtsec</rules>
                <rules>tae</rules>
                <rules>rfts</rules>
                <rules>risk</rules>
                <package platform="win32" version="0.4.1">
                    <file href="http://thousandparsec.net/tp/downloads/tpserver-cpp/tpserver-cpp-0.4.1-win32.zip">Download from Thousand Parsec Website</file>
                    <file href="http://sourceforge.net/project/downloading.php?group_id=132078&amp;filename=tpserver-cpp-0.4.1-win32.zip">Download from SourceForge</file>
                </package>
                <package platform="linux-ubuntu" version="0.6.1">
                    <instruction>Run &lt;code&gt;sudo apt-get install tpserver-cpp&lt;/code&gt;.</instruction>
                </package>
                <package platform="linux-debian" version="0.6.1">
                    <instruction>Run &lt;code&gt;sudo apt-get install tpserver-cpp&lt;/code&gt;.</instruction>
                </package>
                <package platform="linux-gentoo" version="0.6.1">
